# Generated by Django 5.0.1 on 2024-01-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing_comment_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_time',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creation_time',
        ),
    ]
