# Generated by Django 5.0.1 on 2024-01-18 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alter_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(blank=True, default='Uncategorized', on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
